### ISSUE TITLE
Empty collection can't be reduced error when calling API on stub http server

### ISSUE THREAD

**Issue by tkrisztian95** [znsio/specmatic-node#113]
**Description**
I have an API specification with one API path that is returning a JSON array of objects. I don't have a template for response and when a request from test hit the stub server it causes a 500 error `Empty collection can't be reduced`.

API specification snippet `service.yaml`
```
---
openapi: "3.0.1"
info:
  title: "Contract for the AI service"
  version: "1"
paths:
  /service/api/v1/templates/list:
    get:
      summary: "Should be able to get templates"
      parameters: # Workaround for local testing https://github.com/znsio/specmatic/issues/577
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            enum:
              [
                "Bearer some token is here...",
              ]
      responses:
        "200":
          description: "An array of templates"
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ArrayOfTemplates'
              examples:
                FETCH_TEMPLATES_SUCCESS:
                  value:
                  - uuid: 16c47839-da6d-4c8d-9c66-5dcb8d8f52bf
                    displayName: My template
                    description: Here comes some text.
components:
  schemas:
    ArrayOfTemplates: # Schema name
      type: array
      items:
        $ref: '#/components/schemas/Template'
    Template: # Schema name
      type: object
      required:
        - "uuid"
        - "displayName"
      properties:
        uuid:
          type: string
          format: uuid
        displayName:
          type: string
```

Console output:
```
[specmatic] 13-12-2023 16:09:23 debug: Stub: 
--------------------
  Request at 2023-12-13 4:9:23.556
    GET /service/api/v1/templates/list
    host: 127.0.0.1:10002
    connection: keep-alive
    accept: application/json
    content-type: application/json
    authorization: Bearer token
    accept-language: *
    sec-fetch-mode: cors
    user-agent: undici
    accept-encoding: gzip, deflate
    
    

  Response at 2023-12-13 4:9:23.581
    500 Internal Server Error
    X-Specmatic-Result: failure
    
    Empty collection can't be reduced
    
    java.lang.UnsupportedOperationException: Empty collection can't be reduced.
        at in.specmatic.stub.HttpStubKt.fakeHttpResponse(HttpStub.kt:1037)
        at in.specmatic.stub.HttpStubKt.getHttpResponse(HttpStub.kt:648)
        at in.specmatic.stub.HttpStub.serveStubResponse(HttpStub.kt:312)
        at in.specmatic.stub.HttpStub.access$serveStubResponse(HttpStub.kt:41)
        at in.specmatic.stub.HttpStub$environment$1$1$2.invokeSuspend(HttpStub.kt:170)
        at in.specmatic.stub.HttpStub$environment$1$1$2.invoke(HttpStub.kt)
        at in.specmatic.stub.HttpStub$environment$1$1$2.invoke(HttpStub.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invokeSuspend(BaseApplicationEngine.kt:124)
        at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)
        at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
        at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invokeSuspend(DefaultEnginePipeline.kt:123)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
        at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:119)
        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
        at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:37)
        at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:29)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Steps to reproduce**
1. Create a file ...
2. Run this command: ...
3. Make an http request looking like this: ...

**Expected behavior**
Returning 200 status code and json array with randomized JSON object.

**Screenshots**

**System Information:**
 - OS & version: Windows 10 WSL Ubuntu
 - Specmatic version: `"^1.0.3"` (package.json)
 - JDK version: 17

**Additional context**
I'm running the test from NodeJS test and it starts the http stub server. Because of https://github.com/znsio/specmatic-node/issues/111 i cannot set/provide a canned response from a `template.json`. If I start the stub server from CLI  by `specmatic stub service.yaml` without the `service_data` and not from the tests it works as expected and return randomized data.

**Comment by joelrosario** [comment]
Hi @tkrisztian95, we have replied to #111 and believe that by resolving that, this will also get resolved.

Meanwhile we do need to improve the error message returned, and have made a note of that at https://github.com/znsio/specmatic/issues/873.
